### PR TITLE
checked out Deliver parking lot with the most predicted open spots task

### PR DESCRIPTION
**Pull request by kevin-rodri**
Checked that off since that's the method worked on. If changes need to be made, I'm more than welcome to work on those changes.

### CODE REVIEW

**Comment by kevin-rodri** [comment]
there was a merge conflict that I had to resolve...

**Review by LittleTealeaf — APPROVED** [review]
Looks good to me

**Review by LittleTealeaf — CHANGES_REQUESTED** [review]
Just a minor change request, as indicated in a comment within the code. Nothing too big, and the rest of the code looks fine

**Review by LittleTealeaf — CHANGES_REQUESTED** [review]
Just some small change requests, as indicated in the other comment. Nothing much just a small best-practices thing

**Pull request merged**
